pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
//        maven { url = 'https://repo.spongepowered.org/repository/maven-public' }
        maven { url = "https://repo.repsy.io/mvn/timeconqueror/common/" }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
